### ISSUE TITLE
Remove bullets in metadata

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/moodle-local_courseblog#2]

**Comment by mjsamberg** [comment]
Updated, moved to staging. Assigned to @adreier for testing.

**Comment by adreier** [comment]
Hmm -- I'm still seeing bullets. 

![screen shot 2017-01-17 at 3 56 42 pm](https://cloud.githubusercontent.com/assets/13201528/22039496/9831a954-dccd-11e6-8ba8-65972ff36bf7.png)

**Comment by adreier** [comment]
Nice -- looks good.
