### ISSUE TITLE
Make blog titles smaller

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/moodle-local_courseblog#3]

**Comment by mjsamberg** [comment]
@adreier How much smaller?

**Comment by adreier** [comment]
![screen shot 2017-01-03 at 2 12 09 pm](https://cloud.githubusercontent.com/assets/13201528/21619667/ab8386a4-d1be-11e6-9791-6f87fbd04c2d.png)

**Comment by mjsamberg** [comment]
Updated, moved to staging. Assigned to @adreier for testing.
